// Generated by https://quicktype.io

export default interface Character {
    info:    Info;
    results: Result[];
}


export  interface Info {
    count: number;
    pages: number;
    next?:  string;
    prev?:  string;
}

export interface Result {
    id:       number;
    name:     string;
    status:   string;  /* reducido a string */
    species:  string;  /* reducido a string */
    type:     string;
    gender:   string;  /* reducido a string */
    origin:   string;  /* reducido a string */
    location: string;  /* reducido a string */
    image:    string;
    price : number;
    episode:  string[];
    url:      string;
    created:  string;
}




